-- Instalação completa; para banco existente use migrations/semanas_6_7.sql.
-- Instalação nova inclui restrição de ACL; não altera RLS. Ver IMPLANTACAO_SEGURA.md.

create table if not exists dicas (
    id_dica bigint generated by default as identity primary key,
    titulo text not null,
    descricao text
);

insert into dicas (titulo, descricao)
select sementes.titulo, sementes.descricao from (values
    ('Comece devagar', 'Nas primeiras semanas, priorize a constância em vez da intensidade.'),
    ('Hidratação', 'Beba água antes, durante e depois do treino.'),
    ('Aquecimento', 'Cinco minutos de aquecimento reduzem bastante o risco de lesão.')
) as sementes(titulo, descricao)
where not exists (select 1 from dicas where dicas.titulo = sementes.titulo);

-- Tabela de usuarios (cadastro/login - Semana 2).
-- A senha nunca e guardada em texto puro, apenas o hash gerado pelo werkzeug.
-- O Flask consulta esta tabela com a chave configurada no ambiente.
create table if not exists usuarios (
    id_usuario bigint generated by default as identity primary key,
    nome text not null,
    email text not null unique,
    senha_hash text not null,
    criado_em timestamptz not null default now()
);

-- Definições para instalação nova; não recriam tabelas existentes.
create table if not exists public.atividades (
    id_atividade bigint generated by default as identity primary key,
    id_usuario bigint not null references public.usuarios(id_usuario),
    tipo_exercicio text not null,
    duracao integer not null check (duracao > 0),
    frequencia integer not null check (frequencia between 1 and 7),
    data_registro timestamptz not null default now()
);

create table if not exists public.metas (
    id_meta bigint generated by default as identity primary key,
    id_usuario bigint not null references public.usuarios(id_usuario),
    descricao text not null,
    prazo date not null,
    progresso integer not null default 0 check (progresso between 0 and 100)
);

create table if not exists public.agenda (
    id_agenda bigint generated by default as identity primary key,
    id_usuario bigint not null references public.usuarios(id_usuario),
    horario timestamp without time zone not null,
    lembrete text
);

create table if not exists public.conquistas (
    id_conquista bigint generated by default as identity primary key,
    nome text not null,
    descricao text not null,
    pontos integer not null default 0
);

create table if not exists public.usuario_conquista (
    id_usuario bigint not null references public.usuarios(id_usuario),
    id_conquista bigint not null references public.conquistas(id_conquista),
    data_obtencao date not null default (now() at time zone 'America/Sao_Paulo')::date,
    primary key (id_usuario, id_conquista)
);

-- SEMANAS 6 E 7 (mesmo SQL de migrations/semanas_6_7.sql)
-- Execute integralmente no SQL Editor do Supabase.
-- Atualização mínima do banco existente, conferido na auditoria final.
-- Preserve SUPABASE_KEY e as permissões/RLS atuais. Não exige service_role.
-- Pré-requisito: tabelas existentes do projeto (ver schema.sql para banco novo).
-- Para conferir permissões e constraints sem alterações, use
-- migrations/auditoria_somente_leitura.sql antes desta migração.
begin;

-- Não modifica horario, lembrete, IDs ou registros existentes.
alter table public.agenda add column if not exists titulo varchar(120)
    not null default 'Treino agendado';

-- Se houver duplicações preexistentes, falha e reverte a transação; não apaga dados.
create unique index if not exists usuario_conquista_usuario_conquista_uidx
    on public.usuario_conquista (id_usuario, id_conquista);

-- Mantém os três nomes já cadastrados. Não altera pontos existentes.
-- Pontos das novas conquistas = 0; nenhuma lógica de XP é implementada.
insert into public.conquistas (nome, descricao, pontos)
select s.nome, s.descricao, 0 from (values
    ('Primeiro passo', 'Registrou a primeira atividade física.'),
    ('Semana cheia', 'Treinou sete dias seguidos.'),
    ('Meta batida', 'Concluiu a primeira meta.'),
    ('Em Movimento', 'Realizou cinco atividades.'),
    ('Foco Total', 'Realizou dez atividades.'),
    ('Veterano', 'Realizou trinta atividades.')
) as s(nome, descricao)
where not exists (select 1 from public.conquistas c where lower(btrim(c.nome)) = lower(btrim(s.nome)));

create index if not exists atividades_usuario_data_idx on public.atividades (id_usuario, data_registro);
create index if not exists metas_usuario_prazo_idx on public.metas (id_usuario, prazo);
create index if not exists agenda_usuario_horario_idx on public.agenda (id_usuario, horario);

-- Não executa GRANT, REVOKE, mudanças de RLS/policies ou de sequências.

notify pgrst, 'reload schema';

commit;

-- Alertas previstos no modelo; a tabela já existe no ambiente real.
create table if not exists public.alertas (
    id_alerta bigint generated by default as identity primary key,
    mensagem text not null,
    tipo text not null,
    data_hora timestamp not null default now(),
    status text not null default 'nao_lido',
    id_usuario bigint not null references public.usuarios(id_usuario)
);
-- Execute integralmente no SQL Editor do Supabase.
-- A tabela public.alertas já existe no banco real. Não altera permissões/RLS.
begin;
alter table public.alertas add column if not exists chave_evento text;
-- Registros legados sem chave são preservados. NULL não conflita no índice.
create unique index if not exists alertas_usuario_evento_uidx
    on public.alertas (id_usuario, chave_evento);
notify pgrst, 'reload schema';
commit;

-- SEGURANÇA: restringir acesso à API ao servidor Flask.
-- PROPOSTA LOCAL: exige revisão/autorização específica de permissões.
-- Executar como postgres, em manutenção, APÓS configurar o Flask com chave
-- exclusiva de servidor (sb_secret_... ou JWT service_role). Ambas usam o papel
-- service_role. Com anon/sb_publishable_... o Flask deixará de funcionar.
-- Não cria papéis, não altera RLS/policies, não apaga dados.
begin;
do $$
begin
 if current_user <> 'postgres' then raise exception 'Execute como postgres'; end if;
 if (select count(*) from pg_roles where rolname in ('anon','authenticated','service_role'))<>3 then
   raise exception 'Papéis API obrigatórios ausentes';
 end if;
 if not exists(select 1 from pg_roles where rolname='anon')
 or not exists(select 1 from pg_roles where rolname='authenticated')
 or not exists(select 1 from pg_roles where rolname='service_role' and rolbypassrls) then
   raise exception 'Papéis Supabase esperados ausentes/incompatíveis';
 end if;
end $$;

-- Impede criação/substituição de objetos no schema utilizado pelos triggers.
revoke create on schema public from public, anon, authenticated, service_role;
grant usage on schema public to service_role;
create schema if not exists lifes_private authorization postgres;
revoke all on schema lifes_private from public, anon, authenticated, service_role;

-- Restrição somente às tabelas deste aplicativo; revisar outros consumidores.
-- Revogar a ACL de tabela não basta quando existem privilégios por coluna.
do $$
declare tabela text; coluna record; seq text; funcao record;
begin
 foreach tabela in array array['usuarios','atividades','metas','agenda',
   'conquistas','usuario_conquista','alertas','dicas','recompensas_xp'] loop
   if to_regclass('public.'||tabela) is null then
     if tabela='recompensas_xp' then continue; end if;
     raise exception 'Tabela obrigatória ausente: %',tabela;
   end if;
   execute format('revoke all on table public.%I from public, anon, authenticated, service_role',tabela);
   for coluna in select attname from pg_attribute
      where attrelid=to_regclass('public.'||tabela) and attnum>0 and not attisdropped loop
     execute format('revoke select (%1$I), insert (%1$I), update (%1$I), references (%1$I) on public.%2$I from public, anon, authenticated, service_role',coluna.attname,tabela);
   end loop;
   execute format('grant select on public.%I to service_role',tabela);
   if tabela='usuarios' then
     grant insert on public.usuarios to service_role;
   elsif tabela='usuario_conquista' then
     grant insert on public.usuario_conquista to service_role;
   elsif tabela in ('atividades','metas','agenda','alertas') then
     execute format('grant insert, update, delete on public.%I to service_role',tabela);
   end if;
   for seq in select pg_get_serial_sequence('public.'||tabela,a.attname)
       from pg_attribute a where a.attrelid=to_regclass('public.'||tabela)
       and a.attnum>0 and not a.attisdropped loop
     if seq is not null then
       execute format('revoke all on sequence %s from public, anon, authenticated, service_role',seq);
       if tabela in ('usuarios','atividades','metas','agenda','alertas') then
         execute format('grant usage, select on sequence %s to service_role',seq);
       end if;
     end if;
   end loop;
 end loop;
 for funcao in select p.oid::regprocedure as assinatura from pg_proc p
   join pg_namespace n on n.oid=p.pronamespace
   where n.nspname='public' and p.pronargs=0 and p.prorettype='trigger'::regtype
     and p.proname in ('lifes_validar_registro','lifes_premiar',
                       'lifes_proteger_livro','lifes_estornar_atividade') loop
   execute format('revoke all on function %s from public, anon, authenticated, service_role',funcao.assinatura);
 end loop;
end $$;

-- Gate compartilhado pelas duas migrações: verifica privilégios EFETIVOS,
-- incluindo herança e grants por coluna. Não altera heranças desconhecidas.
create or replace function lifes_private.exigir_backend_privado() returns void
language plpgsql security invoker set search_path=pg_catalog as $$
declare papel record; tabela record; privilegio text; seq text; objeto record;
begin
 if current_user <> 'postgres' then raise exception 'Execute como postgres'; end if;
 if (select count(*) from pg_roles where rolname in ('anon','authenticated','service_role'))<>3 then
   raise exception 'Papéis API obrigatórios ausentes';
 end if;
 if not exists(select 1 from pg_roles where rolname='service_role' and rolbypassrls)
    or not has_schema_privilege('service_role','public','USAGE') then
   raise exception 'service_role requer BYPASSRLS e USAGE no schema public';
 end if;
 for objeto in select nome from unnest(array['usuarios','atividades','metas','agenda',
   'conquistas','usuario_conquista','alertas','dicas']) e(nome) loop
   if not exists(select 1 from pg_class where oid=to_regclass('public.'||objeto.nome)
                 and relkind in ('r','p')) then
     raise exception 'Tabela obrigatória ausente/incompatível: public.%',objeto.nome;
   end if;
 end loop;
 if (select nspowner from pg_namespace where nspname='lifes_private')
    is distinct from (select oid from pg_roles where rolname='postgres') then
   raise exception 'Schema lifes_private deve pertencer a postgres';
 end if;
 for papel in select oid,rolname,rolsuper,rolcreaterole from pg_roles
   where rolname in ('anon','authenticated','service_role') loop
   if papel.rolsuper or papel.rolcreaterole or pg_has_role(papel.oid,'postgres','MEMBER')
      or has_schema_privilege(papel.oid,'public','CREATE')
      or has_schema_privilege(papel.oid,'lifes_private','CREATE') then
     raise exception 'Papel API com acesso administrativo/CREATE: %',papel.rolname;
   end if;
   for tabela in select c.oid,c.relname,c.relowner from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relname in ('usuarios','atividades','metas','agenda',
       'conquistas','usuario_conquista','alertas','dicas','recompensas_xp') loop
     -- Usa os privilégios disponíveis nesta versão, incluindo MAINTAIN quando
     -- suportado, sem passar nomes desconhecidos a versões anteriores.
     for privilegio in select privilege_type from aclexplode(acldefault('r',tabela.relowner)) loop
       if papel.rolname='service_role' and (
          privilegio='SELECT'
          or (privilegio='INSERT' and tabela.relname in ('usuarios','atividades','metas','agenda','usuario_conquista','alertas'))
          or (privilegio in ('UPDATE','DELETE') and tabela.relname in ('atividades','metas','agenda','alertas'))) then
         if not has_table_privilege(papel.oid,tabela.oid,privilegio) then
           raise exception 'Permissão necessária ao Flask ausente: %.% em public.%',papel.rolname,privilegio,tabela.relname;
         end if;
         continue;
       end if;
       if has_table_privilege(papel.oid,tabela.oid,privilegio)
          or (privilegio in ('SELECT','INSERT','UPDATE','REFERENCES')
              and has_any_column_privilege(papel.oid,tabela.oid,privilegio)) then
         raise exception 'Privilégio residual %.% em %; revisar herança/ACL',papel.rolname,privilegio,tabela.relname;
       end if;
     end loop;
     for seq in select pg_get_serial_sequence('public.'||tabela.relname,a.attname)
       from pg_attribute a where a.attrelid=tabela.oid and a.attnum>0 and not a.attisdropped loop
       if seq is null then continue; end if;
       foreach privilegio in array array['USAGE','SELECT','UPDATE'] loop
         if papel.rolname='service_role' and privilegio in ('USAGE','SELECT')
           and tabela.relname in ('usuarios','atividades','metas','agenda','alertas') then
           if not has_sequence_privilege(papel.oid,seq,privilegio) then
             raise exception 'Permissão necessária ao Flask ausente: %.% em %',papel.rolname,privilegio,seq;
           end if;
           continue;
         end if;
         if has_sequence_privilege(papel.oid,seq,privilegio) then
           raise exception 'Privilégio residual %.% em sequência %; revisar herança/ACL',papel.rolname,privilegio,seq;
         end if;
       end loop;
     end loop;
   end loop;
   -- Não examina funções internas em auth/storage/extensions como se fossem RPCs
   -- públicas. Extensão instalada em public NÃO é automaticamente confiável:
   -- SQL dinâmico impede provar ausência de acesso ao aplicativo via pg_depend.
   for objeto in select p.oid::regprocedure as assinatura,pg_get_userbyid(p.proowner) as dono,
       (select e.extname from pg_depend d join pg_extension e on e.oid=d.refobjid
        where d.classid='pg_proc'::regclass and d.objid=p.oid
          and d.refclassid='pg_extension'::regclass and d.deptype='e') as extensao
     from pg_proc p join pg_namespace n on n.oid=p.pronamespace
     where n.nspname='public' and p.prosecdef and has_function_privilege(papel.oid,p.oid,'EXECUTE')
     order by p.oid loop
     raise exception 'SECURITY DEFINER acessível: %, papel=%, dono=%, extensão=%',
       objeto.assinatura,papel.rolname,objeto.dono,coalesce(objeto.extensao,'nenhuma')
       using hint='Revisar esta assinatura e seus consumidores. Não revogar funções de extensões em massa nem liberar RPC desconhecida. Nenhuma alteração desta transação foi confirmada.';
   end loop;
   if papel.rolname <> 'service_role' then
    for objeto in select c.oid::regclass as nome,c.reloptions,pg_get_userbyid(c.relowner) as dono
     from pg_class c join pg_namespace n on n.oid=c.relnamespace
     where n.nspname='public' and c.relkind in ('v','m')
       and has_any_column_privilege(papel.oid,c.oid,'SELECT') order by c.oid loop
     raise exception 'View pública legível: %, papel=%, dono=%, opções=%',
       objeto.nome,papel.rolname,objeto.dono,objeto.reloptions
       using hint='Revisar a definição e dependências, inclusive funções e views encadeadas. security_invoker não garante segurança de funções chamadas. Não altera nem apaga a view.';
    end loop;
   end if;
 end loop;
end $$;
alter function lifes_private.exigir_backend_privado() owner to postgres;
revoke all on function lifes_private.exigir_backend_privado() from public,anon,authenticated,service_role;
select lifes_private.exigir_backend_privado();
notify pgrst,'reload schema';
commit;

-- SEMANAS 8 E 9
-- Semanas 8/9. Revisar e autorizar antes de executar no Supabase.
-- Pré-requisitos: schema + semanas_6_7 + alertas_leitura.
-- Requer seguranca_backend.sql autorizada e chave exclusiva do servidor no Flask.
-- Restringe ACL do livro/funções; não modifica RLS nem apaga registros.
begin;
select lifes_private.exigir_backend_privado();
alter table public.dicas add column if not exists categoria text not null default 'Hábitos saudáveis';
alter table public.dicas add column if not exists fonte text;
alter table public.agenda add column if not exists realizado_em timestamptz;
alter table public.atividades add column if not exists chave_registro uuid;
alter table public.atividades add column if not exists id_agenda bigint references public.agenda(id_agenda) on delete set null;
create unique index if not exists atividade_registro_uidx on public.atividades(id_usuario,chave_registro);
create unique index if not exists atividade_agenda_uidx on public.atividades(id_usuario,id_agenda);

create table if not exists public.recompensas_xp (
 id_recompensa bigint generated always as identity primary key,
 id_usuario bigint not null references public.usuarios(id_usuario),
 chave_evento text not null,
 motivo text not null,
 xp integer not null check (xp in (20,30,50)),
 criado_em timestamptz not null default now(),
 unique(id_usuario,chave_evento)
);
-- A tabela pode não existir durante seguranca_backend.sql. Neutraliza seus
-- default grants nesta mesma transação, antes de instalar os triggers.
-- REVOKE na tabela não remove ACL por coluna. Não altera defaults do projeto.
revoke all on public.recompensas_xp from public,anon,authenticated,service_role;
do $$
declare coluna record; seq text;
begin
 for coluna in select attname from pg_attribute
   where attrelid='public.recompensas_xp'::regclass and attnum>0 and not attisdropped loop
   execute format('revoke select (%1$I), insert (%1$I), update (%1$I), references (%1$I) on public.recompensas_xp from public,anon,authenticated,service_role',coluna.attname);
   seq:=pg_get_serial_sequence('public.recompensas_xp',coluna.attname);
   if seq is not null then
     execute format('revoke all on sequence %s from public,anon,authenticated,service_role',seq);
   end if;
 end loop;
end $$;
grant select on public.recompensas_xp to service_role;
-- IF NOT EXISTS não prova a definição de um índice já existente.
-- Recusa índices parciais, inválidos, por expressão ou com colunas diferentes.
do $$
declare esperado record;
begin
 for esperado in select * from (values
   ('atividades',array['id_usuario','chave_registro']),
   ('atividades',array['id_usuario','id_agenda']),
   ('recompensas_xp',array['id_usuario','chave_evento']),
   ('usuario_conquista',array['id_usuario','id_conquista'])
 ) e(tabela,colunas) loop
   if not exists(select 1 from pg_index i
     where i.indrelid=to_regclass('public.'||esperado.tabela)
       and i.indisunique and i.indisvalid and i.indisready and i.indimmediate
       and i.indpred is null and i.indexprs is null
       and (select array_agg(a.attname::text order by k.ord)
            from unnest(i.indkey) with ordinality k(num,ord)
            join pg_attribute a on a.attrelid=i.indrelid and a.attnum=k.num
            where k.ord<=i.indnkeyatts)=esperado.colunas) then
     raise exception 'Unicidade obrigatória incompatível: % (%)',esperado.tabela,esperado.colunas;
   end if;
 end loop;
end $$;
-- Funções internas são invocadas exclusivamente por triggers. SECURITY DEFINER
-- permite gravar o livro interno sem dar escrita nele ao cliente do Flask.
-- search_path fixo e referências qualificadas; nenhuma função recebe usuário via RPC.
create or replace function public.lifes_validar_registro() returns trigger
language plpgsql security definer set search_path = pg_catalog as $$
declare concluido timestamptz;
begin
 if tg_relid <> 'public.atividades'::regclass or tg_when <> 'BEFORE' or tg_op not in ('INSERT','UPDATE') then
   raise exception 'Contexto de trigger inválido';
 end if;
 -- Serializa por usuário também as recompensas de sequência e retries concorrentes.
 perform 1 from public.usuarios where id_usuario=new.id_usuario for update;
 if new.chave_registro is not null and exists (
   select 1 from public.recompensas_xp where id_usuario=new.id_usuario
   and chave_evento='atividade:' || new.chave_registro::text) then return null; end if;
 if new.id_agenda is not null then
   select realizado_em into concluido from public.agenda
   where id_agenda=new.id_agenda and id_usuario=new.id_usuario for update;
   if not found then raise exception 'Treino não pertence ao usuário'; end if;
   if concluido is not null then return null; end if;
 end if;
 if new.tipo_exercicio is null or new.tipo_exercicio not in ('Corrida','Musculação','Ciclismo','Natação','Yoga','Outros')
    or new.duracao is null or new.duracao not between 1 and 1440
    or new.frequencia is null or new.frequencia not between 1 and 7
    or new.data_registro is null or
      (case when pg_typeof(new.data_registro)::text='timestamp without time zone'
        then new.data_registro::timestamp at time zone 'UTC'
        else new.data_registro::timestamptz end) > now() + interval '5 minutes' then
   raise exception 'Atividade inválida';
 end if;
 return new;
end $$;
create or replace function public.lifes_premiar() returns trigger
language plpgsql security definer set search_path = pg_catalog as $$
begin
 if tg_when <> 'AFTER' or not ((tg_relid='public.atividades'::regclass and tg_op in ('INSERT','UPDATE'))
   or (tg_relid='public.metas'::regclass and tg_op='UPDATE')
   or (tg_relid='public.usuario_conquista'::regclass and tg_op='INSERT')) then
   raise exception 'Contexto de recompensa inválido';
 end if;
 perform 1 from public.usuarios where id_usuario=new.id_usuario for update;
 if tg_table_name='atividades' then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(new.id_usuario,'atividade:' || coalesce(new.chave_registro::text,new.id_atividade::text),'Atividade concluída',20)
   on conflict(id_usuario,chave_evento) do nothing;
   if new.id_agenda is not null then
     update public.agenda set realizado_em=now() where id_agenda=new.id_agenda and id_usuario=new.id_usuario;
   end if;
   -- Primeira sequência de sete dias, uma vez na vida. Datas locais reais.
   if exists (
     select 1 from (
       select dia, dia - (row_number() over(order by dia))::integer as grupo
       from (select distinct (case when pg_typeof(data_registro)::text='timestamp without time zone'
               then (data_registro::timestamp at time zone 'UTC') at time zone 'America/Sao_Paulo'
               else data_registro::timestamptz at time zone 'America/Sao_Paulo' end)::date as dia
             from public.atividades where id_usuario=new.id_usuario and
               (case when pg_typeof(data_registro)::text='timestamp without time zone'
                 then data_registro::timestamp at time zone 'UTC'
                 else data_registro::timestamptz end)<=now()) d
     ) s group by grupo having count(*)>=7
   ) then
     insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
     values(new.id_usuario,'sequencia:primeiros-7','Primeira sequência de 7 dias',50)
     on conflict(id_usuario,chave_evento) do nothing;
   end if;
 elsif tg_table_name='metas' then
  if new.progresso=100 and old.progresso<100 then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(new.id_usuario,'meta:' || new.id_meta::text,'Meta concluída',50)
   on conflict(id_usuario,chave_evento) do nothing;
  end if;
 elsif tg_table_name='usuario_conquista' then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(new.id_usuario,'conquista:' || new.id_conquista::text,'Conquista desbloqueada',30)
   on conflict(id_usuario,chave_evento) do nothing;
 end if;
 return new;
end $$;
create or replace trigger lifes_validar_atividade before insert on public.atividades
 for each row execute function public.lifes_validar_registro();
create or replace trigger lifes_xp_atividade after insert on public.atividades
 for each row execute function public.lifes_premiar();
create or replace trigger lifes_xp_meta after update on public.metas
 for each row execute function public.lifes_premiar();
create or replace trigger lifes_xp_conquista after insert on public.usuario_conquista
 for each row execute function public.lifes_premiar();

-- A autorização vem das ACLs e do papel efetivo postgres dos triggers internos.
-- Profundidade é apenas uma verificação adicional de contexto, não autorização.
create or replace function public.lifes_proteger_livro() returns trigger
language plpgsql security invoker set search_path = pg_catalog as $$
begin
 if current_user <> 'postgres' or tg_relid <> 'public.recompensas_xp'::regclass
    or tg_op <> 'INSERT' or pg_trigger_depth() < 2 then
   raise exception 'O histórico de XP só aceita recompensas dos eventos internos';
 end if;
 return new;
end $$;
create or replace trigger lifes_livro_imutavel before insert or update or delete
 on public.recompensas_xp for each row execute function public.lifes_proteger_livro();
create or replace trigger lifes_livro_sem_truncate before truncate
 on public.recompensas_xp for each statement execute function public.lifes_proteger_livro();

insert into public.dicas(titulo,descricao,categoria,fonte)
select s.* from (values
 ('Movimento que cabe no seu dia','Comece com uma atividade que você gosta e aumente o tempo gradualmente. Caminhar e usar escadas também contam. Adapte a intensidade às suas possibilidades.','Atividade física','https://www.who.int/news-room/fact-sheets/detail/physical-activity'),
 ('Recuperação faz parte do treino','Alterne dias intensos e leves e observe como se sente. Descanso é parte da rotina. Dor persistente ou mal-estar merecem avaliação profissional.','Recuperação','https://www.cdc.gov/physical-activity-basics/'),
 ('Uma rotina para dormir melhor','Procure manter horários regulares e um ambiente tranquilo para dormir. Reduza telas perto da hora de deitar. Necessidades de sono variam; dificuldades persistentes merecem orientação.','Sono','https://www.cdc.gov/sleep/about/'),
 ('Água por perto','Tenha água disponível durante o dia e ao se exercitar. Calor e esforço mudam as necessidades. Não há um volume único adequado a todas as pessoas; siga orientações profissionais se tiver restrições.','Hidratação','https://www.cdc.gov/healthy-weight-growth/water-healthy-drinks/'),
 ('Pequenos hábitos, constância possível','Escolha uma mudança pequena e observe como ela se encaixa na sua rotina. Registre o que conseguiu fazer e ajuste o plano sem culpa. Não é preciso treinar todos os dias para cuidar de si.','Hábitos saudáveis','https://www.who.int/news-room/fact-sheets/detail/physical-activity')
) s(titulo,descricao,categoria,fonte)
where not exists(select 1 from public.dicas d where d.titulo=s.titulo);
-- Corrige afirmação absoluta do seed antigo sem apagar a dica.
update public.dicas set descricao='Prepare-se com movimentos leves e aumente o esforço gradualmente. O aquecimento deve considerar a atividade e suas possibilidades.', categoria='Atividade física'
where titulo='Aquecimento' and descricao='Cinco minutos de aquecimento reduzem bastante o risco de lesão.';

-- Privilégios de escrita não são necessários para o cliente Flask: apenas SELECT.
-- BYPASSRLS de service_role não concede INSERT quando a ACL o nega.
revoke all on public.recompensas_xp from public,anon,authenticated,service_role;
grant select on public.recompensas_xp to service_role;
do $$
declare seq text;
begin
 if (select relowner from pg_class where oid='public.recompensas_xp'::regclass)
    <> (select oid from pg_roles where rolname='postgres') then
   raise exception 'Proprietário do livro deve ser postgres; revisar antes de migrar';
 end if;
 seq:=pg_get_serial_sequence('public.recompensas_xp','id_recompensa');
 if seq is not null then execute format('revoke all on sequence %s from public,anon,authenticated,service_role',seq); end if;
end $$;
alter function public.lifes_validar_registro() owner to postgres;
revoke all on function public.lifes_validar_registro() from public,anon,authenticated,service_role;
alter function public.lifes_premiar() owner to postgres;
revoke all on function public.lifes_premiar() from public,anon,authenticated,service_role;
alter function public.lifes_proteger_livro() owner to postgres;
revoke all on function public.lifes_proteger_livro() from public,anon,authenticated,service_role;
select lifes_private.exigir_backend_privado();

notify pgrst,'reload schema';
commit;

-- FINALIZAÇÃO PREMIUM
-- Revisar e autorizar antes de executar. Requer semanas_8_9.sql.
-- Requer também seguranca_backend.sql. Preserva linhas, frequência legada e RLS.
-- ACL das funções internas é restrita; histórico permanece imutável.
begin;
select lifes_private.exigir_backend_privado();
alter table public.atividades alter column frequencia drop not null;
comment on column public.atividades.frequencia is
 'Frequência semanal declarada em registros legados. Novas sessões usam NULL; nunca multiplica sessões.';
alter table public.agenda add column if not exists modalidade text;

create or replace function public.lifes_validar_registro() returns trigger
language plpgsql security definer set search_path = pg_catalog as $$
declare concluido timestamptz;
begin
 if tg_relid <> 'public.atividades'::regclass or tg_when <> 'BEFORE' or tg_op not in ('INSERT','UPDATE') then
   raise exception 'Contexto de trigger inválido';
 end if;
 perform 1 from public.usuarios where id_usuario=new.id_usuario for update;
 if tg_op='UPDATE' then
   if new.id_usuario is distinct from old.id_usuario
      or new.chave_registro is distinct from old.chave_registro
      or (new.id_agenda is distinct from old.id_agenda and new.id_agenda is not null) then
     raise exception 'Identidade da sessão não pode ser alterada';
   end if;
   -- ON DELETE SET NULL da agenda deve preservar inclusive registros legados.
   if new.id_agenda is null and old.id_agenda is not null
      and new.tipo_exercicio=old.tipo_exercicio and new.duracao=old.duracao
      and new.data_registro=old.data_registro then return new; end if;
 else
   if new.chave_registro is not null and exists (
     select 1 from public.recompensas_xp where id_usuario=new.id_usuario
       and chave_evento='atividade:' || new.chave_registro::text) then return null; end if;
   if new.id_agenda is not null then
     select realizado_em into concluido from public.agenda
       where id_agenda=new.id_agenda and id_usuario=new.id_usuario for update;
     if not found then raise exception 'Treino não pertence ao usuário'; end if;
     if concluido is not null then return null; end if;
   end if;
 end if;
 if new.tipo_exercicio is null or new.tipo_exercicio not in
   ('Corrida','Musculação','Ciclismo','Natação','Yoga','Artes Marciais','Outros')
   or new.duracao is null or new.duracao not between 1 and 1440
   or (new.frequencia is not null and new.frequencia not between 1 and 7)
   or new.data_registro is null or
     (case when pg_typeof(new.data_registro)::text='timestamp without time zone'
       then new.data_registro::timestamp at time zone 'UTC'
       else new.data_registro::timestamptz end) > now() + interval '5 minutes' then
   raise exception 'Atividade inválida';
 end if;
 return new;
end $$;
create or replace trigger lifes_validar_atividade before insert or update on public.atividades
 for each row execute function public.lifes_validar_registro();

create or replace function public.lifes_premiar() returns trigger
language plpgsql security definer set search_path = pg_catalog as $$
begin
 if tg_when <> 'AFTER' or not ((tg_relid='public.atividades'::regclass and tg_op in ('INSERT','UPDATE'))
   or (tg_relid='public.metas'::regclass and tg_op='UPDATE')
   or (tg_relid='public.usuario_conquista'::regclass and tg_op='INSERT')) then
   raise exception 'Contexto de recompensa inválido';
 end if;
 perform 1 from public.usuarios where id_usuario=new.id_usuario for update;
 if tg_table_name='atividades' then
  if tg_op='INSERT' then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(new.id_usuario,'atividade:' || coalesce(new.chave_registro::text,new.id_atividade::text),'Atividade concluída',20)
   on conflict(id_usuario,chave_evento) do nothing;
   if new.id_agenda is not null then
     update public.agenda set realizado_em=now() where id_agenda=new.id_agenda and id_usuario=new.id_usuario;
   end if;
  elsif new.data_registro is not distinct from old.data_registro then
    return new;
  end if;
   -- A edição da data pode alcançar o marco; duração/tipo não repetem XP.
   -- Timestamp legado sem offset representa UTC, como no cálculo Python.
   if exists (
     select 1 from (
       select dia, dia - (row_number() over(order by dia))::integer as grupo
       from (select distinct (case when pg_typeof(data_registro)::text='timestamp without time zone'
               then (data_registro::timestamp at time zone 'UTC') at time zone 'America/Sao_Paulo'
               else data_registro::timestamptz at time zone 'America/Sao_Paulo' end)::date as dia
             from public.atividades where id_usuario=new.id_usuario and
               (case when pg_typeof(data_registro)::text='timestamp without time zone'
                 then data_registro::timestamp at time zone 'UTC'
                 else data_registro::timestamptz end)<=now()) d
     ) s group by grupo having count(*)>=7
   ) then
     insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
     values(new.id_usuario,'sequencia:primeiros-7','Primeira sequência de 7 dias',50)
     on conflict(id_usuario,chave_evento) do nothing;
   end if;
 elsif tg_table_name='metas' then
  if new.progresso=100 and old.progresso<100 then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(new.id_usuario,'meta:' || new.id_meta::text,'Meta concluída',50)
   on conflict(id_usuario,chave_evento) do nothing;
  end if;
 elsif tg_table_name='usuario_conquista' then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(new.id_usuario,'conquista:' || new.id_conquista::text,'Conquista desbloqueada',30)
   on conflict(id_usuario,chave_evento) do nothing;
 end if;
 return new;
end $$;
create or replace trigger lifes_xp_atividade after insert or update on public.atividades
 for each row execute function public.lifes_premiar();

-- O lançamento original é mantido; a exclusão acrescenta um estorno único.
alter table public.recompensas_xp drop constraint if exists recompensas_xp_xp_check;
alter table public.recompensas_xp add constraint recompensas_xp_xp_check
 check (xp in (-20,20,30,50));
create or replace function public.lifes_estornar_atividade() returns trigger
language plpgsql security definer set search_path = pg_catalog as $$
declare evento text;
begin
 if tg_relid <> 'public.atividades'::regclass or tg_op <> 'DELETE' or tg_when <> 'AFTER' then
   raise exception 'Contexto de estorno inválido';
 end if;
 perform 1 from public.usuarios where id_usuario=old.id_usuario for update;
 evento := 'atividade:' || coalesce(old.chave_registro::text,old.id_atividade::text);
 if exists(select 1 from public.recompensas_xp where id_usuario=old.id_usuario
    and chave_evento=evento and xp=20) then
   insert into public.recompensas_xp(id_usuario,chave_evento,motivo,xp)
   values(old.id_usuario,'estorno:' || evento,'Estorno de atividade excluída',-20)
   on conflict(id_usuario,chave_evento) do nothing;
 end if;
 return old;
end $$;
create or replace trigger lifes_estorno_atividade after delete on public.atividades
 for each row execute function public.lifes_estornar_atividade();

-- Duplicações anteriores abortam a migração para revisão; nunca apagar/mesclar IDs.
lock table public.conquistas in share row exclusive mode;
create unique index if not exists conquistas_nome_normalizado_uidx
 on public.conquistas(pg_catalog.lower(pg_catalog.btrim(nome)));
do $$
declare caminho_anterior text := current_setting('search_path');
begin
 -- Referência vazia com os MESMOS tipos/collations das colunas reais. O parser
 -- insere os casts corretos (ex.: varchar -> text), sem ler/copiar conquistas.
 -- Não compara com SQL literal nem remove casts/qualificações por regex.
 perform set_config('search_path','pg_catalog,pg_temp',true);
 create temporary table lifes_conquistas_indice_ref
   (like public.conquistas) on commit drop;
 create unique index lifes_conquistas_indice_ref_uidx
   on lifes_conquistas_indice_ref(pg_catalog.lower(pg_catalog.btrim(nome)));
 if not exists(select 1 from pg_index i
   join pg_class atual on atual.oid=i.indexrelid
   cross join pg_index esperado
   join pg_class referencia on referencia.oid=esperado.indexrelid
   where i.indexrelid=to_regclass('public.conquistas_nome_normalizado_uidx')
     and esperado.indexrelid=to_regclass('pg_temp.lifes_conquistas_indice_ref_uidx')
     and i.indrelid='public.conquistas'::regclass
     and i.indisunique and i.indisvalid and i.indisready and i.indislive
     and i.indimmediate and not i.indisexclusion
     and i.indnkeyatts=1 and i.indkey[0]=0 and i.indpred is null
     and atual.relam=referencia.relam
     and i.indclass=esperado.indclass and i.indcollation=esperado.indcollation
     -- Ambos reconstruídos pelo mesmo servidor/search_path a partir das árvores
     -- analisadas: aceita casts de tipo e nomes qualificados equivalentes.
     and pg_get_expr(i.indexprs,i.indrelid,false)
         =pg_get_expr(esperado.indexprs,esperado.indrelid,false)) then
   raise exception 'Índice de nomes normalizados incompatível; revisar sem remover dados';
 end if;
 perform set_config('search_path',caminho_anterior,true);
end $$;
-- Seed completo dos 14 critérios, preservando nomes/IDs/pontos existentes.
insert into public.conquistas(nome,descricao,pontos)
select s.nome,s.descricao,0 from (values
 ('Primeiro passo','Realize sua primeira atividade.'),
 ('Em Movimento','Realize 5 atividades.'),
 ('Foco Total','Realize 10 atividades.'),
 ('Veterano','Realize 30 atividades.'),
 ('Semana cheia','Registre atividades em 7 dias consecutivos.'),
 ('Meta batida','Conclua uma meta (100% de progresso).'),
 ('Lenda do Treino','Realize 100 atividades.'),
 ('Constância de Aço','Registre atividades em 14 dias consecutivos.'),
 ('Imparável','Registre atividades em 30 dias consecutivos.'),
 ('Caçador de Metas','Conclua 5 metas.'),
 ('Mestre dos Objetivos','Conclua 10 metas.'),
 ('Uma Hora de Superação','Acumule 60 minutos de atividades.'),
 ('Dez Horas de Evolução','Acumule 600 minutos de atividades.'),
 ('Centurião','Acumule 6.000 minutos de atividades.')
) s(nome,descricao)
where not exists(select 1 from public.conquistas c where lower(trim(c.nome))=lower(s.nome));
alter function public.lifes_validar_registro() owner to postgres;
revoke all on function public.lifes_validar_registro() from public,anon,authenticated,service_role;
alter function public.lifes_premiar() owner to postgres;
revoke all on function public.lifes_premiar() from public,anon,authenticated,service_role;
alter function public.lifes_estornar_atividade() owner to postgres;
revoke all on function public.lifes_estornar_atividade() from public,anon,authenticated,service_role;
select lifes_private.exigir_backend_privado();

notify pgrst,'reload schema';
commit;
