-- Execute este script no SQL Editor do Supabase para criar as tabelas iniciais.
-- Lembre-se de desabilitar o Row Level Security (ou criar uma policy de SELECT
-- publico) na tabela "dicas" para que a rota /api/teste consiga ler os dados.

create table if not exists dicas (
    id_dica bigint generated by default as identity primary key,
    titulo text not null,
    descricao text
);

insert into dicas (titulo, descricao) values
    ('Comece devagar', 'Nas primeiras semanas, priorize a constância em vez da intensidade.'),
    ('Hidratação', 'Beba água antes, durante e depois do treino.'),
    ('Aquecimento', 'Cinco minutos de aquecimento reduzem bastante o risco de lesão.');
