-- Execute este script no SQL Editor do Supabase para criar as tabelas iniciais.
-- Lembre-se de desabilitar o Row Level Security (ou criar uma policy de SELECT
-- publico) na tabela "dicas" para que a rota /api/teste consiga ler os dados.

create table if not exists dicas (
    id_dica bigint generated by default as identity primary key,
    titulo text not null,
    descricao text
);

insert into dicas (titulo, descricao) values
    ('Comece devagar', 'Nas primeiras semanas, priorize a constância em vez da intensidade.'),
    ('Hidratação', 'Beba água antes, durante e depois do treino.'),
    ('Aquecimento', 'Cinco minutos de aquecimento reduzem bastante o risco de lesão.');

-- Tabela de usuarios (cadastro/login - Semana 2).
-- A senha nunca e guardada em texto puro, apenas o hash gerado pelo werkzeug.
-- Assim como em "dicas", desabilite o RLS (ou crie policies de select/insert
-- publicas) para que a anon key usada pelo Flask consiga ler e escrever aqui.
create table if not exists usuarios (
    id_usuario bigint generated by default as identity primary key,
    nome text not null,
    email text not null unique,
    senha_hash text not null,
    criado_em timestamptz not null default now()
);
